swagger: "2.0"
info:
  version: "1.0.0"
  title: "GO-12 01: Синхронное взаимодействие через REST"
host: "server-domain"
schemes:
- "http"
paths:
  /send:
    post:
      summary: "Send file to pdf compose"
      consumes:
         - multipart/form-data
      parameters:
        - in: formData
          name: upfile1
          type: file
          required: true
        - in: formData
          name: upfile2
          type: file
          required: false
        - in: formData
          name: upfile3
          type: file
          required: false
      produces:
        - application/pdf
      responses:
        "200":
          description: A PDF file.
          schema:
            type: file
        "400":
          description: "Bad request"
        "500":
          description: "Internal Server Error"